version: "3.9"
services:
  nextjs:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - ./secrets/firebase-key.json:/app/secrets/firebase-key.json:ro
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

